use serde::{Deserialize, Serialize};
use sqlx::types::chrono::NaiveDateTime;
use uuid::Uuid;

#[derive(Debug, Serialize, Deserialize, sqlx::FromRow)]
pub struct ApiKey {
    pub id: Uuid,
    pub name: String,
    pub encrypt_enabled: bool,
    pub encrypt_algorithm: Option<String>,
    pub encrypt_mode: Option<String>,
    pub encrypt_padding: Option<String>,
    pub encrypt_key: Option<String>,
    pub encrypt_iv_source: Option<String>,
    pub encrypt_iv_start: Option<i32>,
    pub encrypt_iv_length: Option<i32>,
    pub encrypt_encoding: Option<String>,
    pub encrypt_join_template: Option<String>,
    pub encrypt_param_name: Option<String>,
    pub sign_enabled: bool,
    pub sign_algorithm: Option<String>,
    pub sign_template: Option<String>,
    pub sign_salt: Option<String>,
    pub sign_param_name: Option<String>,
    pub sign_position: Option<String>,
    pub sign_case: Option<String>,
    pub request_method: Option<String>,
    pub request_base_url: Option<String>,
    pub request_success_check: Option<String>,
    pub env_vars: Option<serde_json::Value>,
    pub tasks: Option<serde_json::Value>,
    pub status: Option<String>,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
}

#[derive(Debug, Deserialize)]
pub struct CreateApiKey {
    pub name: String,
    pub encrypt_enabled: Option<bool>,
    pub encrypt_algorithm: Option<String>,
    pub encrypt_mode: Option<String>,
    pub encrypt_padding: Option<String>,
    pub encrypt_key: Option<String>,
    pub encrypt_iv_source: Option<String>,
    pub encrypt_iv_start: Option<i32>,
    pub encrypt_iv_length: Option<i32>,
    pub encrypt_encoding: Option<String>,
    pub encrypt_join_template: Option<String>,
    pub encrypt_param_name: Option<String>,
    pub sign_enabled: Option<bool>,
    pub sign_algorithm: Option<String>,
    pub sign_template: Option<String>,
    pub sign_salt: Option<String>,
    pub sign_param_name: Option<String>,
    pub sign_position: Option<String>,
    pub sign_case: Option<String>,
    pub request_method: Option<String>,
    pub request_base_url: Option<String>,
    pub request_success_check: Option<String>,
    pub env_vars: Option<serde_json::Value>,
    pub tasks: Option<serde_json::Value>,
    pub status: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct UpdateApiKey {
    pub name: Option<String>,
    pub encrypt_enabled: Option<bool>,
    pub encrypt_algorithm: Option<String>,
    pub encrypt_mode: Option<String>,
    pub encrypt_padding: Option<String>,
    pub encrypt_key: Option<String>,
    pub encrypt_iv_source: Option<String>,
    pub encrypt_iv_start: Option<i32>,
    pub encrypt_iv_length: Option<i32>,
    pub encrypt_encoding: Option<String>,
    pub encrypt_join_template: Option<String>,
    pub encrypt_param_name: Option<String>,
    pub sign_enabled: Option<bool>,
    pub sign_algorithm: Option<String>,
    pub sign_template: Option<String>,
    pub sign_salt: Option<String>,
    pub sign_param_name: Option<String>,
    pub sign_position: Option<String>,
    pub sign_case: Option<String>,
    pub request_method: Option<String>,
    pub request_base_url: Option<String>,
    pub request_success_check: Option<String>,
    pub env_vars: Option<serde_json::Value>,
    pub tasks: Option<serde_json::Value>,
    pub status: Option<String>,
}